// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizzApplication.Data;

#nullable disable

namespace QuizzApplication.Migrations
{
    [DbContext(typeof(QuestionsContext))]
    [Migration("20240424143923_particularQuestionModel1")]
    partial class particularQuestionModel1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizzApplication.Model.Questions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("optionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("optionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("optionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("optionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
